
- name:           Asegurar que el servicio de apache es reiniciado si ha habido cambios
  systemd:
    name:         "{{ constants.service[ ansible_distribution ] }}"
    state:        restarted
  tags:
                - configuracion
  listen:         reinicio-requerido
  become:         True