
# Asegurar que el directorio del document root existe
- name:             Asegurar que cada virtual host quede configurado
  include_tasks:    tasks/asegurar.configuracion.virtualhost.tasks.yaml
  loop:             "{{ apache.virtual_hosts }}"
  loop_control:
    loop_var:       virtualhost