
- name:       Asegurar que el servicio de Apache quedar activado
  systemd:
    name:     "{{ constants.service[ ansible_distribution ] }}"
    enabled:  true
  become:   True

- name:       Asegurar que el servicio de Apache quedar arrancado
  systemd:
    name:     "{{ constants.service[ ansible_distribution ] }}"
    state:    started
  become:   True
    