  
- name: Asegurar que apache queda instalado en la versión indicada
  include_tasks: util/install.package.{{ansible_distribution}}.yaml
  vars:
    packages_to_install: 
      - name:     apache2
        version:  "{{ apache.version }}"
        repos:    "{{ apache.repos | default( [] ) }}"

- name: Asegurar que los módulos de apache solicitados quedan instalados en la versión solicitada
  include_tasks: util/install.package.{{ansible_distribution}}.yaml
  vars:
    packages_to_install: "{{ apache.apache_modules }}"
  notify: reinicio-requerido
