
- name:       Asegurar que el servicio de Apache quedar activado
  systemd:
    name:     "{{ constants.service_name[ ansible_distribution ] }}"
    enabled:  true

- name:       Asegurar que el servicio de Apache quedar arrancado
  systemd:
    name:     "{{ constants.service_name[ ansible_distribution ] }}"
    state:    started