- name:               Instalación y configuración de un servidor web Apache
  hosts:              all
  gather_facts:       False

  pre_tasks:

    - name:           Cargar variables
      import_tasks:   pre_tasks/cargar.variables.tasks.yaml
      tags:
                    - always      # always never: Son tags especiales de Ansible (PREDEFINIDOS POR ANSIBLE)

    - name:           Asegurar que el host es compatible con este playbook
      import_tasks:   pre_tasks/asegurar.compatibilidad.tasks.yaml
      tags:
                    - always

    - name:           Asegurar que el host soporta la instalación de apache
      import_tasks:   pre_tasks/asegurar.entorno.tasks.yaml
      tags:
                    - requisitos

    - name:           Asegurar que tengo las dependencias necesarias
      import_tasks:   pre_tasks/asegurar.dependencias.tasks.yaml
      tags:
                    - requisitos

  tasks:

    - name:           Asegurar que Apache queda instalado en la versión deseada
      import_tasks:   tasks/asegurar.instalacion.apache.tasks.yaml
      tags:
                    - instalacion

    - name:           Asegurar que los virtual hosts están configurados
      import_tasks:   tasks/asegurar.configuracion.virtualhosts.tasks.yaml
      tags:
                    - configuracion
    
    - meta:           flush_handlers  # OJO: Si el servicio no está arrancado,
                                      # Lo arrancaremos en la siguiente tarea
                                      # Pero... Los handlers lo reiniciarán.
                                      # Y queremos evitarlo.
                                      # Si lanzamos ahora los handlers
                                      # Los handlers lo inciarán
                                      # y la siguiente tarea (por la idempotencia del módulo)
                                      # no hará nada!
                                      
                                      # Esto es igual a cuando en programación imperativa 
                                      # usábamos la palabra proscrita: GOTO

    - name:           Asegurar que el servicio de apache queda en ejecución
      import_tasks:   tasks/asegurar.servicio.apache.tasks.yaml
      tags:
                    - configuracion

  post_tasks:

    - name:           Comprobar que todo ha quedado configurado como debe
      import_tasks:   post_tasks/comprobar.apache.tasks.yaml
      tags:
                    - pruebas

  handlers:

    - name:           Asegurar que el servicio de apache es reiniciado si ha habido cambios
      import_tasks:   handlers/handlers.tasks.yaml


